    { value: "itching", label: "Itching" },
    { value: "skin_rash", label: "Skin rash" },
    { value: "nodal_skin_eruptions", label: "Nodal skin eruptions" },
    { value: "continuous_sneezing", label: "Continuous sneezing" },
    { value: "shivering", label: "Shivering" },
    { value: "chills", label: "Chills" },
    { value: "joint_pain", label: "Joint pain" },
    { value: "stomach_pain", label: "Stomach pain" },
    { value: "acidity", label: "Acidity" },
    { value: "ulcers_on_tongue", label: "Ulcers on tongue" },
    { value: "muscle_wasting", label: "Muscle wasting" },
    { value: "vomiting", label: "Vomiting" },
    { value: "burning_micturition", label: "Burning micturition" },
    { value: "spotting_ urination", label: "Urination" },
    { value: "fatigue", label: "Fatigue" },
    { value: "weight_gain", label: "Weight gain" },
    { value: "anxiety", label: "Anxiety" },
    { value: "cold_hands_and_feets", label: "Cold hands and feets" },
    { value: "mood_swings", label: "Mood swings" },
    { value: "weight_loss", label: "Weight loss" },
    { value: "restlessness", label: "Restlessness" },
    { value: "lethargy", label: "Lethargy" },
    { value: "patches_in_throat", label: "Patches in throat" },
    { value: "irregular_sugar_level", label: "Irregular sugar level" },
    { value: "cough", label: "Cough" },
    { value: "high_fever", label: "High fever" },
    { value: "sunken_eyes", label: "Sunken_eyes" },
    { value: "breathlessness", label: "Breathlessness" },
    { value: "sweating", label: "Sweating" },
    { value: "dehydration", label: "Dehydration" },
    { value: "indigestion", label: "Indigestion" },
    { value: "headache", label: "Headache" },
    { value: "yellowish_skin", label: "Yellowish_skin" },
    { value: "dark_urine", label: "Dark urine" },
    { value: "nausea", label: "Nausea" },
    { value: "loss_of_appetite", label: "Loss of appetite" },
    { value: "pain_behind_the_eyes", label: "Pain behind the eyes" },
    { value: "back_pain", label: "Back pain" },
    { value: "constipation", label: "Constipation" },
    { value: "abdominal_pain", label: "Abdominal pain" },
    { value: "diarrhoea", label: "Diarrhoea" },
    { value: "mild_fever", label: "Mild fever" },
    { value: "yellow_urine", label: "Yellow urine" },
    { value: "yellowing_of_eyes", label: "Yellowing ofeyes" },
    { value: "acute_liver_failure", label: "Acute liver failure" },
    { value: "fluid_overload", label: "Fluid overload" },
    { value: "swelling_of_stomach", label: "Swelling of stomach" },
    { value: "swelled_lymph_nodes", label: "Swelled lymph nodes" },
    { value: "malaise", label: "Malaise" },
    { value: "blurred_and_distorted vision", label: "Blurred and distorted vision" },
    { value: "phlegm", label: "Phlegm" },
    { value: "throat_irritation", label: "Throat irritation" },
    { value: "redness_of_eyes", label: "Redness of eyes" },
    { value: "sinus_pressure", label: "Sinus pressure" },
    { value: "runny_nose", label: "Runny nose" },
    { value: "congestion", label: "Congestion" },
    { value: "chest_pain", label: "Chest pain" },
    { value: "weakness_in_limbs", label: "Weakness in limbs" },
    { value: "fast_heart_rate", label: "Fast heart rate" },
    { value: "pain_during_bowel_movements", label: "Pain during bowel movements" },
    { value: "pain_in_anal_region", label: "Pain in anal region" },
    { value: "bloody_stool", label: "Bloodystool" },
    { value: "irritation_in_anus", label: "Irritation in anus" },
    { value: "neck_pain", label: "Neck pain" },
    { value: "dizziness", label: "Dizziness" },
    { value: "cramps", label: "Cramps" },
    { value: "bruising", label: "Bruising" },
    { value: "obesity", label: "Obesity" },
    { value: "swollen_legs", label: "Swollen legs" },
    { value: "swollen_blood_vessels", label: "Swollen blood vessels" },
    { value: "puffy_face_and_eyes", label: "Puffy face and eyes" },
    { value: "enlarged_thyroid", label: "Enlarged thyroid" },
    { value: "brittle_nails", label: "Brittle nails" },
    { value: "swollen_extremeties", label: "Swollen extremeties" },
    { value: "excessive_hunger", label: "Excessive hunger" },
    { value: "extra_marital_contacts", label: "Extra marital contacts" },
    { value: "drying_and_tingling_lips", label: "Drying and tingling lips" },
    { value: "slurred_speech", label: "Slurred speech" },
    { value: "knee_pain", label: "Knee pain" },
    { value: "hip_joint_pain", label: "Hip joint pain" },
    { value: "muscle_weakness", label: "Muscle weakness" },
    { value: "stiff_neck", label: "Stiff neck" },
    { value: "swelling_joints", label: "Swelling joints" },
    { value: "movement_stiffness", label: "Movement stiffness" },
    { value: "spinning_movements", label: "Spinning movements" },
    { value: "loss_of_balance", label: "Loss of balance" },
    { value: "unsteadiness", label: "Unsteadiness" },
    { value: "weakness_of_one_body_side", label: "Weakness of one body side" },
    { value: "loss_of_smell", label: "Loss of smell" },
    { value: "bladder_discomfort", label: "Bladder discomfort" },
    { value: "foul_smell_of urine", label: "Urine" },
    { value: "continuous_feel_of_urine", label: "Continuous feel of urine" },
    { value: "passage_of_gases", label: "Passage of gases" },
    { value: "internal_itching", label: "Internal itching" },
    { value: "toxic_look_(typhos)", label: "toxic_look_(typhos)" },
    { value: "depression", label: "Depression" },
    { value: "irritability", label: "Irritability" },
    { value: "muscle_pain", label: "Muscle pain" },
    { value: "altered_sensorium", label: "Altered sensorium" },
    { value: "red_spots_over_body", label: "Red spots over body" },
    { value: "belly_pain", label: "Belly pain" },
    { value: "abnormal_menstruation", label: "Abnormal menstruation" },
    { value: "dischromic _patches", label: "dischromic patches" },
    { value: "watering_from_eyes", label: "Watering from eyes" },
    { value: "increased_appetite", label: "Increased appetite" },
    { value: "polyuria", label: "Polyuria" },
    { value: "family_history", label: "Family history" },
    { value: "mucoid_sputum", label: "Mucoid sputum" },
    { value: "rusty_sputum", label: "Rusty sputum" },
    { value: "lack_of_concentration", label: "Lack ofconcentration" },
    { value: "visual_disturbances", label: "Visual disturbances" },
    { value: "receiving_blood_transfusion", label: "Receiving blood transfusion" },
    { value: "receiving_unsterile_injections", label: "Receiving unsterile injections" },
    { value: "coma", label: "Coma" },
    { value: "stomach_bleeding", label: "Stomach bleeding" },
    { value: "distention_of_abdomen", label: "Distention of abdomen" },
    { value: "history_of_alcohol_consumption", label: "History of alcohol consumption" },
    { value: "fluid_overload", label: "Fluid overload" },
    { value: "blood_in_sputum", label: "Blood in sputum" },
    { value: "prominent_veins_on_calf", label: "Prominent veins on calf" },
    { value: "palpitations", label: "Palpitations" },
    { value: "painful_walking", label: "Painful walking" },
    { value: "pus_filled_pimples", label: "Pus filled pimples" },
    { value: "blackheads", label: "Blackheads" },
    { value: "scurring", label: "Scurring" },
    { value: "skin_peeling", label: "Skin peeling" },
    { value: "silver_like_dusting", label: "Silver like dusting" },
    { value: "small_dents_in_nails", label: "Small dents in nails" },
    { value: "inflammatory_nails", label: "Inflammatory nails" },
    { value: "blister", label: "Blister" },
    { value: "red_sore_around_nose", label: "Red sore around nose" },
    { value: "yellow_crust_ooze", label: "Yellow crust ooze" }
]